// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import { SAMPLES } from "./support/component-samples.mjs";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-component";

test("obix-component-radiogroup: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["createRadioGroup"], owner0["createRadioGroup"], "createRadioGroup");
  assert.deepEqual(Object.keys(shim0).sort(), ["createRadioGroup","renderRadioGroup"]);
});

test("renderRadioGroup(config, overrides) renders what createRadioGroup(config) renders, with the overrides applied", () => {
  const sample = SAMPLES["RadioGroup"];
  assert.ok(sample, "no sample configuration for RadioGroup");
  // component ids are deterministic counters (createId): reset before each build so two builds of one configuration are comparable
  owner0.resetObixIds();
  const built = owner0.createRadioGroup(sample.config);
  owner0.resetObixIds();
  assert.equal(shim0.renderRadioGroup(sample.config), built.render(built.state));
  const key = Object.keys(built.state).find((k) => typeof built.state[k] === "boolean");
  owner0.resetObixIds();
  if (key) assert.equal(shim0.renderRadioGroup(sample.config, { [key]: !built.state[key] }), built.render({ ...built.state, [key]: !built.state[key] }));
});
