// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createRadioGroup, renderWith } from "obix-core-component";
export { createRadioGroup } from "obix-core-component";
export type { RadioGroupConfig, RadioGroupState, RadioOption } from "obix-core-component";
export const renderRadioGroup = renderWith(createRadioGroup);
